export const INIT_ROUTE_DATA_REQUEST = 'INIT_ROUTE_DATA_REQUEST';
export const INIT_ROUTE_LOADING = 'INIT_ROUTE_LOADING';

export const SET_ROUTE_DATA_SUCCESS = 'SET_ROUTE_DATA_SUCCESS';

export const SET_ROUTE_DATA_ERROR = 'SET_ROUTE_DATA_ERROR ';
